export const types = {
  sendAnswer: '[Trivia] Answer',
  setCorrectAnswer: '[Trivia] Set Answer',
  setSuccess: '[Trivia] Set Success',
  setFail: '[Trivia] Set Fail',
  loadNextQuestion: '[Trivia] Load Next Question',
  increaseQuestionNumber: '[Trivia] Increase Question Number',
  revealSolution: '[Trivia] Reveal Solution',
  disableOptions: '[Trivia] Disable options',
  setGameOver: '[Trivia] Set Game Over',
  beginTrivia: '[Trivia] Begin Trivia',
  setRetry: '[Trivia] Set Retry',
  setMenu: '[Trivia] Set Menu',
  setRegions: '[Trivia] Set Regions',
}